// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/rpc/rpc.proto

package iotexrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_UNKNOWN       MessageType = 0
	MessageType_ACTION        MessageType = 1
	MessageType_BLOCK         MessageType = 2
	MessageType_CONSENSUS     MessageType = 3
	MessageType_BLOCK_REQUEST MessageType = 4
	MessageType_TEST          MessageType = 10001
)

var MessageType_name = map[int32]string{
	0:     "UNKNOWN",
	1:     "ACTION",
	2:     "BLOCK",
	3:     "CONSENSUS",
	4:     "BLOCK_REQUEST",
	10001: "TEST",
}

var MessageType_value = map[string]int32{
	"UNKNOWN":       0,
	"ACTION":        1,
	"BLOCK":         2,
	"CONSENSUS":     3,
	"BLOCK_REQUEST": 4,
	"TEST":          10001,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59d40974ffbedc26, []int{0}
}

type BlockSync struct {
	Start                uint64   `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  uint64   `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockSync) Reset()         { *m = BlockSync{} }
func (m *BlockSync) String() string { return proto.CompactTextString(m) }
func (*BlockSync) ProtoMessage()    {}
func (*BlockSync) Descriptor() ([]byte, []int) {
	return fileDescriptor_59d40974ffbedc26, []int{0}
}

func (m *BlockSync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockSync.Unmarshal(m, b)
}
func (m *BlockSync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockSync.Marshal(b, m, deterministic)
}
func (m *BlockSync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockSync.Merge(m, src)
}
func (m *BlockSync) XXX_Size() int {
	return xxx_messageInfo_BlockSync.Size(m)
}
func (m *BlockSync) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockSync.DiscardUnknown(m)
}

var xxx_messageInfo_BlockSync proto.InternalMessageInfo

func (m *BlockSync) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *BlockSync) GetEnd() uint64 {
	if m != nil {
		return m.End
	}
	return 0
}

type BroadcastMsg struct {
	ChainId              uint32               `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	MsgType              MessageType          `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3,enum=iotexrpc.MessageType" json:"msg_type,omitempty"`
	MsgBody              []byte               `protobuf:"bytes,3,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	PeerId               string               `protobuf:"bytes,4,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BroadcastMsg) Reset()         { *m = BroadcastMsg{} }
func (m *BroadcastMsg) String() string { return proto.CompactTextString(m) }
func (*BroadcastMsg) ProtoMessage()    {}
func (*BroadcastMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_59d40974ffbedc26, []int{1}
}

func (m *BroadcastMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastMsg.Unmarshal(m, b)
}
func (m *BroadcastMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastMsg.Marshal(b, m, deterministic)
}
func (m *BroadcastMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastMsg.Merge(m, src)
}
func (m *BroadcastMsg) XXX_Size() int {
	return xxx_messageInfo_BroadcastMsg.Size(m)
}
func (m *BroadcastMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastMsg proto.InternalMessageInfo

func (m *BroadcastMsg) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *BroadcastMsg) GetMsgType() MessageType {
	if m != nil {
		return m.MsgType
	}
	return MessageType_UNKNOWN
}

func (m *BroadcastMsg) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

func (m *BroadcastMsg) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *BroadcastMsg) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type UnicastMsg struct {
	ChainId              uint32               `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Addr                 string               `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	MsgType              MessageType          `protobuf:"varint,3,opt,name=msg_type,json=msgType,proto3,enum=iotexrpc.MessageType" json:"msg_type,omitempty"`
	MsgBody              []byte               `protobuf:"bytes,4,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	PeerId               string               `protobuf:"bytes,5,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UnicastMsg) Reset()         { *m = UnicastMsg{} }
func (m *UnicastMsg) String() string { return proto.CompactTextString(m) }
func (*UnicastMsg) ProtoMessage()    {}
func (*UnicastMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_59d40974ffbedc26, []int{2}
}

func (m *UnicastMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnicastMsg.Unmarshal(m, b)
}
func (m *UnicastMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnicastMsg.Marshal(b, m, deterministic)
}
func (m *UnicastMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnicastMsg.Merge(m, src)
}
func (m *UnicastMsg) XXX_Size() int {
	return xxx_messageInfo_UnicastMsg.Size(m)
}
func (m *UnicastMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UnicastMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UnicastMsg proto.InternalMessageInfo

func (m *UnicastMsg) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *UnicastMsg) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *UnicastMsg) GetMsgType() MessageType {
	if m != nil {
		return m.MsgType
	}
	return MessageType_UNKNOWN
}

func (m *UnicastMsg) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

func (m *UnicastMsg) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *UnicastMsg) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterEnum("iotexrpc.MessageType", MessageType_name, MessageType_value)
	proto.RegisterType((*BlockSync)(nil), "iotexrpc.BlockSync")
	proto.RegisterType((*BroadcastMsg)(nil), "iotexrpc.BroadcastMsg")
	proto.RegisterType((*UnicastMsg)(nil), "iotexrpc.UnicastMsg")
}

func init() { proto.RegisterFile("proto/rpc/rpc.proto", fileDescriptor_59d40974ffbedc26) }

var fileDescriptor_59d40974ffbedc26 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0xc9, 0x36, 0xfd, 0x93, 0xe9, 0x16, 0x05, 0x03, 0xa2, 0xec, 0x85, 0xaa, 0xa7, 0x8a,
	0x83, 0xb3, 0xda, 0xbd, 0x70, 0x25, 0x55, 0x0f, 0xd5, 0xb2, 0xa9, 0x48, 0x52, 0x21, 0x71, 0xa0,
	0x72, 0x6d, 0xe3, 0x06, 0x9a, 0xd8, 0xb2, 0xbd, 0x12, 0x79, 0x0c, 0x1e, 0x8b, 0x67, 0xe0, 0x65,
	0x90, 0x5d, 0x85, 0x3f, 0x87, 0x95, 0xd8, 0x43, 0xa4, 0xef, 0x9b, 0x99, 0xcc, 0x7c, 0x3f, 0xc3,
	0x53, 0xa5, 0xa5, 0x95, 0x89, 0x56, 0xd4, 0x7d, 0xd8, 0x3b, 0x34, 0xaa, 0xa4, 0xe5, 0xdf, 0xb4,
	0xa2, 0x17, 0xaf, 0x84, 0x94, 0xe2, 0xc8, 0x13, 0x5f, 0xdf, 0xdf, 0x7d, 0x4e, 0x6c, 0x55, 0x73,
	0x63, 0x49, 0xad, 0x4e, 0xa3, 0xf3, 0x6b, 0x88, 0xd2, 0xa3, 0xa4, 0x5f, 0x8b, 0xb6, 0xa1, 0xe8,
	0x19, 0xf4, 0x8d, 0x25, 0xda, 0x4e, 0xcf, 0x66, 0xc1, 0x22, 0xcc, 0x4f, 0x06, 0xc5, 0xd0, 0xe3,
	0x0d, 0x9b, 0xf6, 0x7c, 0xcd, 0xc9, 0xf9, 0x8f, 0x00, 0xce, 0x53, 0x2d, 0x09, 0xa3, 0xc4, 0xd8,
	0x5b, 0x23, 0xd0, 0x4b, 0x18, 0xd1, 0x03, 0xa9, 0x9a, 0x5d, 0xc5, 0xa6, 0xc1, 0x2c, 0x58, 0x4c,
	0xf2, 0xa1, 0xf7, 0x6b, 0x86, 0x2e, 0x61, 0x54, 0x1b, 0xb1, 0xb3, 0xad, 0xe2, 0x7e, 0xed, 0xe3,
	0xab, 0xe7, 0xb8, 0x8b, 0x87, 0x6f, 0xb9, 0x31, 0x44, 0xf0, 0xb2, 0x55, 0x3c, 0x1f, 0xd6, 0x46,
	0x38, 0xe1, 0x96, 0xb9, 0x3f, 0xf6, 0x92, 0xb5, 0xfe, 0xe8, 0xb9, 0x6f, 0xa5, 0x92, 0xb5, 0xe8,
	0x05, 0x0c, 0x15, 0xe7, 0xda, 0x9d, 0x09, 0x67, 0xc1, 0x22, 0xca, 0x07, 0xce, 0xae, 0x19, 0x7a,
	0x03, 0xd1, 0x6f, 0xb2, 0x69, 0x7f, 0x16, 0x2c, 0xc6, 0x57, 0x17, 0xf8, 0xc4, 0x8e, 0x3b, 0x76,
	0x5c, 0x76, 0x13, 0xf9, 0x9f, 0xe1, 0xf9, 0xcf, 0x00, 0x60, 0xdb, 0x54, 0xff, 0x41, 0x82, 0x20,
	0x24, 0x8c, 0x69, 0x4f, 0x11, 0xe5, 0x5e, 0xff, 0x43, 0xd7, 0x7b, 0x30, 0x5d, 0x78, 0x2f, 0x5d,
	0xff, 0x7e, 0xba, 0xc1, 0x03, 0xe8, 0x5e, 0x7f, 0x82, 0xf1, 0x5f, 0x29, 0xd0, 0x18, 0x86, 0xdb,
	0xec, 0x26, 0xdb, 0x7c, 0xc8, 0xe2, 0x47, 0x08, 0x60, 0xf0, 0x76, 0x59, 0xae, 0x37, 0x59, 0x1c,
	0xa0, 0x08, 0xfa, 0xe9, 0xbb, 0xcd, 0xf2, 0x26, 0x3e, 0x43, 0x13, 0x88, 0x96, 0x9b, 0xac, 0x58,
	0x65, 0xc5, 0xb6, 0x88, 0x7b, 0xe8, 0x09, 0x4c, 0x7c, 0x67, 0x97, 0xaf, 0xde, 0x6f, 0x57, 0x45,
	0x19, 0x87, 0x28, 0x82, 0xb0, 0x74, 0xea, 0x7b, 0x96, 0x5e, 0x7e, 0xc4, 0xa2, 0xb2, 0x87, 0xbb,
	0x3d, 0xa6, 0xb2, 0x4e, 0x3c, 0xb9, 0xd2, 0xf2, 0x0b, 0xa7, 0x36, 0x51, 0x07, 0xa2, 0xa5, 0x49,
	0x84, 0x3c, 0x92, 0x46, 0x24, 0xdd, 0xa3, 0xec, 0x07, 0x3e, 0xf0, 0xf5, 0xaf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x4c, 0x89, 0xfa, 0xf9, 0xb9, 0x02, 0x00, 0x00,
}
